on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: macOS-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
    
      - name: Install dependencies
        run: Rscript -e 'install.packages("rtweet", dependencies= TRUE)'
           
      - name: Generate data
        run: Rscript fetctweet.R
    
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
      



